<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dakshagrithav" failures="2" tests="8" name="OpenCart Tests" time="88.415" errors="0" timestamp="2022-06-29T21:07:41 GMT+08:00">
  <testcase classname="testCases.TC_001_AccountRegistration" name="test_accout_Registration" time="5.433"/>
  <testcase classname="testCases.TC_002_Login" name="test_Login" time="12.97">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_002_Login.test_Login(TC_002_Login.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_Login -->
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="3.162"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="11.567"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="11.679"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="11.469"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="11.464"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="11.552">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_LoginDDT.test_LoginDDT(TC_003_LoginDDT.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_LoginDDT -->
</testsuite> <!-- OpenCart Tests -->
